### PR TITLE
Support configuration of tags on launcher

### PR DESCRIPTION
**Pull request by leandroeo**
This commit enhance the configuration to support including tags for the launcher.

### CODE REVIEW

**Comment by leandroeo** [comment]
This is a kind of enhancement on the change of  [Pull Request Add tags parameter #18](https://github.com/reportportal/agent-js-jasmine/pull/18).
As the tags was ignored when the 'id' is present.

**Comment by leandroeo** [comment]
This is a kind of enhancement on the change of [Pull Request Add tags parameter #18](https://github.com/reportportal/agent-js-jasmine/pull/18).
As the tags was ignored when the 'id' is present.

**Comment by leandroeo** [comment]
As @BorisOsipov already reviewed, can you @avarabyeu @DzmitryHumianiuk have a look to merge it?

Thanks in advance 😄

**Comment by leandroeo** [comment]
Can we merge it? @BorisOsipov @avarabyeu @DzmitryHumianiuk

**Comment by sabaya** [comment]
Hi! When are you planning a new release of npm package with this feature?

We are choosing solution to store Protractor's autotests results and we need to store machine configuration(browser name, OS, etc). ReportPortal's tags can be a good solution for this. Could you please release agent-js-jasmine with this feature?

**Comment by DzmitryHumianiuk** [comment]
@sabaya 
need a time to fix release job 
```
npm ERR! publish Failed PUT 403
npm ERR! code E403
npm ERR! You cannot publish over the previously published versions: 1.0.0. : reportportal-agent-jasmine

npm ERR! A complete log of this run can be found in:
```

**Pull request merged**
